apiVersion: v1
kind: Secret
metadata:
  name: qaenv-sample
type: Opaque
data:
  githubPAT: Z2l0aHViX3BhdF8xMUFOMjZDTlkwd3o3QWdvZUhrS2lhX0RDbnNaazV6WU9wTFFXZDh5MkhDTFFJem4wME5USHl0Z0NDbFowVlppUEVHTENKSTdTWDBMNHBRNFMz
