//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/fluxcd/pkg/apis/meta"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coordinator) DeepCopyInto(out *Coordinator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coordinator.
func (in *Coordinator) DeepCopy() *Coordinator {
	if in == nil {
		return nil
	}
	out := new(Coordinator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Coordinator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinatorList) DeepCopyInto(out *CoordinatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Coordinator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinatorList.
func (in *CoordinatorList) DeepCopy() *CoordinatorList {
	if in == nil {
		return nil
	}
	out := new(CoordinatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoordinatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinatorSpec) DeepCopyInto(out *CoordinatorSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	out.Interval = in.Interval
	in.QAEnvTemplate.DeepCopyInto(&out.QAEnvTemplate)
	out.SourceRef = in.SourceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinatorSpec.
func (in *CoordinatorSpec) DeepCopy() *CoordinatorSpec {
	if in == nil {
		return nil
	}
	out := new(CoordinatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinatorStatus) DeepCopyInto(out *CoordinatorStatus) {
	*out = *in
	if in.TicketMap != nil {
		in, out := &in.TicketMap, &out.TicketMap
		*out = make(map[string]*TicketMap, len(*in))
		for key, val := range *in {
			var outVal *TicketMap
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(TicketMap)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.QaEnvs != nil {
		in, out := &in.QaEnvs, &out.QaEnvs
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinatorStatus.
func (in *CoordinatorStatus) DeepCopy() *CoordinatorStatus {
	if in == nil {
		return nil
	}
	out := new(CoordinatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePolicySpec) DeepCopyInto(out *ImagePolicySpec) {
	*out = *in
	out.ImageRepositoryRef = in.ImageRepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePolicySpec.
func (in *ImagePolicySpec) DeepCopy() *ImagePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ImagePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizationSpec) DeepCopyInto(out *KustomizationSpec) {
	*out = *in
	out.SourceRef = in.SourceRef
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizationSpec.
func (in *KustomizationSpec) DeepCopy() *KustomizationSpec {
	if in == nil {
		return nil
	}
	out := new(KustomizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequest) DeepCopyInto(out *PullRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequest.
func (in *PullRequest) DeepCopy() *PullRequest {
	if in == nil {
		return nil
	}
	out := new(PullRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QAEnv) DeepCopyInto(out *QAEnv) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QAEnv.
func (in *QAEnv) DeepCopy() *QAEnv {
	if in == nil {
		return nil
	}
	out := new(QAEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QAEnv) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QAEnvList) DeepCopyInto(out *QAEnvList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QAEnv, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QAEnvList.
func (in *QAEnvList) DeepCopy() *QAEnvList {
	if in == nil {
		return nil
	}
	out := new(QAEnvList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QAEnvList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QAEnvSpec) DeepCopyInto(out *QAEnvSpec) {
	*out = *in
	if in.ImagePolicies != nil {
		in, out := &in.ImagePolicies, &out.ImagePolicies
		*out = make([]ImagePolicySpec, len(*in))
		copy(*out, *in)
	}
	out.KustomizationSpec = in.KustomizationSpec
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QAEnvSpec.
func (in *QAEnvSpec) DeepCopy() *QAEnvSpec {
	if in == nil {
		return nil
	}
	out := new(QAEnvSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QAEnvStatus) DeepCopyInto(out *QAEnvStatus) {
	*out = *in
	if in.Kustomization != nil {
		in, out := &in.Kustomization, &out.Kustomization
		*out = new(meta.NamespacedObjectReference)
		**out = **in
	}
	if in.ImagePolicies != nil {
		in, out := &in.ImagePolicies, &out.ImagePolicies
		*out = make(map[string]*meta.NamespacedObjectReference, len(*in))
		for key, val := range *in {
			var outVal *meta.NamespacedObjectReference
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(meta.NamespacedObjectReference)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QAEnvStatus.
func (in *QAEnvStatus) DeepCopy() *QAEnvStatus {
	if in == nil {
		return nil
	}
	out := new(QAEnvStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QAEnvTemplate) DeepCopyInto(out *QAEnvTemplate) {
	*out = *in
	out.Interval = in.Interval
	if in.QaEnvs != nil {
		in, out := &in.QaEnvs, &out.QaEnvs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QAEnvTemplate.
func (in *QAEnvTemplate) DeepCopy() *QAEnvTemplate {
	if in == nil {
		return nil
	}
	out := new(QAEnvTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TicketMap) DeepCopyInto(out *TicketMap) {
	*out = *in
	if in.QAEnvIndex != nil {
		in, out := &in.QAEnvIndex, &out.QAEnvIndex
		*out = new(string)
		**out = **in
	}
	if in.PullRequestsMap != nil {
		in, out := &in.PullRequestsMap, &out.PullRequestsMap
		*out = make(map[string]PullRequest, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TicketMap.
func (in *TicketMap) DeepCopy() *TicketMap {
	if in == nil {
		return nil
	}
	out := new(TicketMap)
	in.DeepCopyInto(out)
	return out
}
